// Geçerli tahminler sözlüğü (örnek). Çözüm kelimeleri de dahil olmalı.
export const VALID_WORDS: readonly string[] = [
    "kalem","şehir","ışık","üzgün","çizgi","güneş","kavun","sütlü","köprü","kargo","deniz",
    "ağacı","ağrıı","akşam","aklım","alevi","alıcı","altın","anlam","arada","araba","balık",
    "banka","başka","bebek","beşer","bilet","bilgi","bölüm","böyle","ceviz","cevap","cazip",
    "çadır","çalış","çamur","çanta","çayır","çekir","çelik","çıkış","çoğuı","çocuk","daima",
    "dalga","danış","defne","diken","dilci","doğal","dolar","dostu","döner","dürüm","düşün",
    "eczac","ekmek","eleşt","elmas","emekl","emmek","erken","espri","eşsiz","fener","fesle",
    "fikir","fındık","fiyat","fokur","gazet","gizem","göbek","göçük","gölge","görev","gözen",
    "gülme","güneş","gürült","haber","halat","halka","hapis","hasta","hatta","hayal","hızlı",
    "hürri","içeri","içmek","ikili","ikram","ilgin","imkan","indim","inmek","insan","irade",
    "ismin","işlem","işlek","işsiz","jilet","kadar","kafes","kahve","kalem","kalın","kanca",
    "karde","kayık","kayış","kayna","kebap","kefir","kekik","keman","kemik","kents","kervan",
    "kesin","kesme","kibar","kitle","kızıl","kısım","kıyma","kıyıı","kızak","klima","kokus",
    "konut","korel","koyun","kömür","köpek","köprü","kredi","kroki","kural","kurgu","kurul",
    "kuzey","lamba","lazım","leble","lekel","liman","liste","lokum","maden","mahal","mahkû",
    "makas","makul","malz","manga","mantı","marul","masal","masaş","mecaz","meden","mekik",
    "melik","merak","mermi","mesai","mesaj","metin","meyve","mezun","milim","mimar","misal",
    "model","moral","motel","motor","muhit","muhte","muhte","mumya","müjde","müzik","nabız",
    "naif","nakit","nazik","neden","nehir","nesil","nesne","neyse","niçin","nitel","nizam",
    "nuhut","nurcu","ocakt","odacı","odalı","oduns","ofans","ofset","oğlak","okluk","okuma",
    "olası","olgun","olmak","onluk","onurl","opera","oranı","ortak","otlak","otluk","oynak",
    "öğret","öksüz","ölçüm","ölmek","önder","önlem","örnek","örtü","örtme","örtüş","öteki",
    "öykü","özgür","özgül","özlem","öznel","papat","parça","paraş","parka","parla","payet",
    "pazar","pekim","peşin","peynir","pişir","planı","plaza","posta","potas","proje","psiko",
    "radyo","rafet","rahat","rakip","rande","reklam","resim","reyon","riyal","roket","roman",
    "röport","sabır","sabah","sabun","sadef","safra","sağır","sahil","sahip","sakin","salla",
    "salon","sanat","saray","saray","sarma","saten","satır","sayfa","seçim","sedef","sefer",
    "sehir","sekiz","semai","seval","sevin","seyir","sıcak","sihir","simit","simya","simit",
    "sinir","sistem","sitem","sofra","soğuk","somut","sonuç","sorgu","soslu","soyut","soylu",
    "sözde","söğüt","sökmek","sürat","sürme","sütlü","şahin","şapka","şarkı","şeker","şemsi",
    "şerit","şifre","şimdi","şölen","tabak","tabir","tablo","tacir","tahıl","tahmin","takım",
    "taksi","talan","talep","tamam","tanel","tanım","taraf","tarif","tarım","tartı","tasar",
    "tasma","tatlı","tavır","tavan","tavuk","tayfa","tedir","teker","tekil","tekne","teknik",
    "tekrar","telaf","temel","tempo","tenis","tesis","tesir","tesis","teyit","tıpçı","ticari",
    "tilki","tiner","tipik","tiraj","tokat","tokyo","tombu","topak","topla","topuz","torba",
    "töre","tören","tütün","ufkun","uğrak","uğurl","uğurt","ulaş","ultra","umrum","umutl",
    "unvan","urany","usuls","uyarı","uygun","uyruk","uzman","üzere","üzmek","üzücü","vagon",
    "vakıf","vakur","valiz","vakit","varil","varis","varış","vatan","vebal","vekil","velut",
    "vergi","verim","vezir","video","vicda","viski","vizör","vokal","yakıt","yakın","yakut",
    "yalın","yalnız","yaman","yapıt","yapım","yasal","yasak","yatak","yavaş","yazılı","yemek",
    "yerel","yeter","yıldız","yılan","yoksa","yoğun","yolcu","yolun","yonca","yöner","yönet",
    "yufka","yükle","yüzde","yüzey","zahir","zamir","zaten","zayıf","zence","ziraa","ziyad"
];


